version: '3'
services:
  db:
    # DB Credentials
    # adapter: postgresql
    # encoding: unicode
    # host: db
    # username: postgres
    # password:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/base_ror_build #switch out with local folder
    ports:
      - "3000:3000"
    depends_on:
      - db